package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"comments_service/graph/model"
	"context"
	"fmt"
	"log"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, registerData model.RegisterData) (*model.RegisterStatus, error) {
	token, err := r.Uc.Register(ctx, registerData)
	if err != nil {
		log.Println(err)
		buf := fmt.Sprint(err)
		return &model.RegisterStatus{Iserror: true, Description: &buf, Token: nil}, err
	}
	return &model.RegisterStatus{Iserror: false, Description: nil, Token: &token}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
