// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type RegisterData struct {
	Login string `json:"login"`
}

type RegisterStatus struct {
	Iserror     bool    `json:"iserror"`
	Description *string `json:"description,omitempty"`
	Token       *string `json:"token,omitempty"`
}
